services:
  regtest:
    image: "doichain/core:dc0.20.1.15"
    container_name: regtest
    ports:
      - "18332:18332"
      - "18443:18443"
      - "18445:18445"
    volumes:
      - ./docker/doichain-regtest.conf:/home/doichain/.doichain/doichain.conf
      - ./docker/regtest-entrypoint.sh:/home/doichain/regtest-entrypoint.sh
    entrypoint: ["/bin/bash", "/home/doichain/regtest-entrypoint.sh"]

  electrumx:
    container_name: electrumx
    hostname: electrumx
    image: "doichain/electrumx:dc1.2.1"
    depends_on:
      - regtest
    volumes:
      # - ./db:/var/lib/electrumx
      - ./docker/startElectrumDOIRegTest.sh:/startElectrumDOIRegTest.sh
    entrypoint: ["/startElectrumDOIRegTest.sh"]
    ports:
      - "50001:50001"
      - "50002:50002"
      - "8443:8443"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50001"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    stdin_open: true
    tty: true
    privileged: true

  relay-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./docker/entrypoint.sh:/usr/src/app/entrypoint.sh
      # - ./:/usr/src/app/
    entrypoint: ["/usr/src/app/entrypoint.sh", "start"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9090"]  # Check libp2p port instead
      interval: 5s
      timeout: 3s
      retries: 3
    depends_on:
      regtest:
        condition: service_started
      electrumx:
        condition: service_healthy
    ports:
      - "1235:1235"
      - "9090:9090"  # Required for libp2p connectivity
      - "9091:9091"
      - "12345:12345"
      - "3000:3000"
    environment:
      - RELAY_LISTEN_ADDRESSES=/ip4/0.0.0.0/tcp/9090,/ip4/0.0.0.0/tcp/9091
      - RELAY_ANNOUNCE_ADDRESSES=/dns4/relay-service/tcp/9090,/dns4/relay-service/tcp/9091  # Use container DNS name
      - RELAY_DEV_MODE=true  # Enable dev mode for testing
      - RELAY_PRIVATE_KEY=${TEST_RELAY_PRIVATE_KEY}  # Use environment variable for security

volumes:
  doichain-data:
